stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
  
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw
    outs:
      - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/interim
    outs:
      - data/processed
  
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed
    outs:
      - models/model.pkl
  
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed/test_tfidf.csv
    metrics:
      - reports/metrics.json
